### ISSUE TITLE
Accords C#m7 et Dbm7

### ISSUE THREAD

**Issue by Jolus** [aspiers/lilypond#1]
Bonjour,
Pour ces accords, le bon diagramme est le suivant

\storePredefinedDiagram #default-fret-table \chordmode {cis:m7}
                        #ukulele-tuning
                        #"1-2-(;1-2-);o;2-3;"
\storePredefinedDiagram #default-fret-table \chordmode {des:m7}
                        #ukulele-tuning
                        #"1-2-(;1-2-);o;2-3;"
Merci

**Comment by aspiers** [comment]
Désolé, mais je ne comprends pas très bien le français ;-)  This is not the correct location to report bugs with LilyPond.  Please see http://lilypond.org/bug-reports.html
